---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - import_tasks: pam_pwquality.yml
    - import_tasks: user_and_group.yml
    - import_tasks: authorized_keys.yml
    - import_tasks: two_factor.yml
  handlers:
    - import_tasks: handlers/restart_ssh.yml

