- name: Ensure group 'developers' exists
  group:
    name: engineers
    state: present

- name: Create the user 'joshua'
  user:
    name: joshua
    shell: /bin/bash
    password: $6$eozUUozrIBZIkE68$nDhsRHU0EjmpsNG4SsUuE8Z41E2QdnqRXqL6c3sCT7LKC1L4jIk1chsBmOJrWjorzCzGnbQthg2KI1u5uTYb11

- name: Assign 'joshua' to the 'engineers' group
  user:
    name: joshua
    groups: engineers
    append: yes

- name: Create a directory name 'engineering'
  file:
    path: /opt/engineering
    state: directory
    mode: 0750
    group: engineers

- name: Create a file in the engineering directory
  file:
    path: "/opt/engineering/private.txt"
    state: touch
    mode: 0770
    group: engineers